# Site settings
title: CoolerSaver
email: me@claytonerrington.com
url: http://yetisaver.github.io/
description: "Save your cooler today with your new CoolerSaver."

# Contact form: comment the line below if you want to stick with the default PHP contact form
contact: static

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: CoolerSaver
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/cjerrington
  - title: facebook
    url:
  - title: github
    url: https://github.com/yetisaver/yetisaver.github.io

# Postal address (add as many lines as necessary)
address:
  - line: 1310 Ave Q
  - line: Lubbock, TX 79401

# Credits content
credits: 'Site made by <a href="http://claytonerrington.com/">Clayton Errington</a>'

# Build settings
markdown: kramdown
permalink: pretty
